version: "3.2"
services:
    notebook:
        image: jupyter-notebook
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8888:8888"
        environment:
            USE_HTTPS: "no"
            PASSWORD: "12345"
        volumes:
            - ~/.aws:/home/.aws
            - ./notebooks:/home/jovyan/work
